# Generated by Django 6.0.4 on 2026-04-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'CANDIDATE',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'PARTY',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Voter_photo', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('voter_id', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('eligibility', models.BooleanField(default=False)),
                ('vote_status', models.CharField(choices=[('VOTED', 'VOTED'), ('NOT VOTED', 'NOT VOTED')], default='NOT VOTED')),
            ],
            options={
                'verbose_name_plural': 'VOTER',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('candidates', models.ManyToManyField(related_name='elections', to='Voting.candidate')),
            ],
            options={
                'verbose_name_plural': 'ELECTION',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Voting.party'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.voter')),
            ],
            options={
                'verbose_name_plural': 'VOTE',
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
