# Generated by Django 6.0.4 on 2026-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='eligibility',
            field=models.BooleanField(choices=[('ELIGIBLE', 'ELIGIBLE'), ('NOT ELIGIBLE', 'NOT ELIGIBLE')], default='ELIGIBLE'),
        ),
    ]
