# Generated by Django 6.0.4 on 2026-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_alter_voter_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='eligibility',
            field=models.CharField(choices=[('ELIGIBLE', 'ELIGIBLE'), ('NOT ELIGIBLE', 'NOT ELIGIBLE')], default='ELIGIBLE', max_length=20),
        ),
    ]
