# Generated by Django 6.0.4 on 2026-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0004_alter_voter_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
