# Generated by Django 6.0.4 on 2026-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0005_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(db_index=True, help_text='Enter the unique National Voter ID number', max_length=200, unique=True),
        ),
    ]
