# Generated by Django 6.0.4 on 2026-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0006_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/%Y/%m/%d'),
        ),
    ]
