# Generated by Django 6.0.4 on 2026-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0007_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/%Y/%m/%d'),
        ),
    ]
