# Generated by Django 6.0.4 on 2026-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0008_party_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='abbreviation',
            field=models.CharField(max_length=200),
        ),
    ]
