# Generated by Django 6.0.4 on 2026-04-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0009_alter_party_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Voting.party', verbose_name='Political Party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='party/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='Voter_photo',
            field=models.ImageField(blank=True, null=True, upload_to='voter/%Y/%m/%d'),
        ),
    ]
