# Generated by Django 6.0.4 on 2026-04-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0010_alter_candidate_party_alter_party_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='Voter_photo',
            new_name='voter_photo',
        ),
    ]
