# Generated by Django 6.0.4 on 2026-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0011_rename_voter_photo_voter_voter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
