# Generated by Django 6.0.4 on 2026-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0012_election_end_time_election_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateField(),
        ),
    ]
